export const AUTH_LOGGING_IN = 'AUTH_LOGGING_IN';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_FAILURE = 'AUTH_FAILURE';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGGING_OUT = 'AUTH_LOGGING_OUT';

export const FETCH_CASES_SUCCESS = 'FETCH_CASES_SUCCESS';
export const FETCH_CASE_FAILURE = 'FETCH_CASE_FAILURE';
export const FETCH_CASES_FAILURE = 'FETCH_CASES_FAILURE';
export const FETCH_CASE_SUCCESS = 'FETCH_CASE_SUCCESS';
export const DESELECT_CASE = 'DESELECT_CASE';

export const START_FETCHING = 'START_FETCHING';
export const STOP_FETCHING = 'STOP_FETCHING';

export const EDIT_CASE_SUCCESS = 'EDIT_CASE_SUCCESS';
export const EDIT_CASE_FAILURE = 'EDIT_CASE_FAILURE';
export const CREATE_CASE_FAILURE = 'CREATE_CASE_FAILURE';
export const CREATE_CASE_SUCCESS = 'CREATE_CASE_SUCCESS';
